# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
python: &python
  docker:
    - image: cimg/python:3.10.11
aws-cli: &awscli
  docker:
    - image: cimg/aws:2023.06
jobs:
  build:
    <<: *python
    steps:
      - checkout
      - run:
          name: install updates
          command: sudo apt-get update 
      - run:
          name: instate upgrades
          command: sudo apt-get upgrade 
      - run: 
          name: install dependencies
          command: sudo apt-get install ffmpeg libsm6 libxext6
      - run:
          name: install python requirments
          command: pip install -r backend/requirements.txt
  create_infrastructure:
    <<: *awscli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack 
          command: aws cloudformation deploy --template-file cf./template.yml --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1
  # test:
  #   <<: *image
  #   steps:
  #     - run: exit 0
  # analyze:
  #   <<: *image
  #   steps:
  #     - run: exit 0
# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  backend: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - create_infrastructure
      # - test:
      #     requires:
      #       - build
      # - analyze:
      #     requires:
      #       - test
