# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
default: &image
  docker:
    - image: cimg/python:3.10.11
jobs:
  build:
    <<: *image
    steps:
      - checkout
      - run:
          name: install updates
          command: apt-get update 
      - run:
          name: instate upgrades
          command: apt-get upgrade 
      - run: 
          name: install dependencies
          command: apt-get install ffmpeg libsm6 libxext6
      - run:
          name: install python requirments
          command: pip install -r backend/requirements.txt
      - run:
          name: Run PIP
          command: pip --version
  # test:
  #   <<: *image
  #   steps:
  #     - run: exit 0
  # analyze:
  #   <<: *image
  #   steps:
  #     - run: exit 0
# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      # - analyze:
      #     requires:
      #       - test
